name = "stripeping"
compatibility_date = "2025-08-19"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "public"

[observability]
enabled = true

[[kv_namespaces]]
binding = "TENANTS"
id = "110384f83ed1467e8a11d6b1d52c198e"
preview_id = "789a40dc68f8470d8afa3abf7c861746"
